baseURL = 'https://javier.caramielo.com.ar/'
languageCode = 'es-ar'
title = 'Pagina Personal'

[menu]
  [[menu.main]]
    identifier = "UNO"
    name = "UNO"
    url = "/uno/"
    weight = 1
    
  [[menu.main]]
    identifier = "DOS"
    name = "DOS"
    url = "/dos/"
    weight = 2
    
  [[menu.main]]
    identifier = "TRES"
    name = "TRES"
    url = "/tres/"
    weight = 3
    
  [[menu.main]]
    identifier = "Novedades"
    name = "Novedades"
    url = "/novedades/"
    weight = 4
    
  [[menu.main]]
    identifier = "Etiquetas"
    name = "Etiquetas"
    pageRef = "tags"
    weight = 5

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"

  [params]
  description = "Documentación"

  [params.search]
    enable = true

[module]
[[module.imports]]
path = "github.com/imfing/hextra"
