baseURL = 'https://javier.caramielo.com.ar/'
languageCode = 'es-ar'
title = 'inicio'

[menu]
  [[menu.main]]
    pageRef = "search"
    weight = -100
    [menu.main.params]
      type = "search"
  [[menu.main]]
    identifier = "VARIOS"
    name = "VARIOS"
    url = "/varios/"
    weight = 1
  [[menu.main]]
    identifier = "PROGRAMACION"
    name = "PROGRAMACION"
    url = "/programacion/"
    weight = 2
  [[menu.main]]
    identifier = "DDHH"
    name = "DDHH"
    url = "/ddhh/"
    weight = 3
  [[menu.main]]
    identifier = "Novedades"
    name = "Novedades"
    url = "/novedades/"
    weight = 4
  [[menu.main]]
    identifier = "Etiquetas"
    name = "Etiquetas"
    pageRef = "tags"
    weight = 5

[params]
  description = "Página Personal"
  pwa = false # Agrego para testear evitar mensaje emergente 27/8/2025

  [params.search]
    enable = true

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"

[module]
  [[module.imports]]
    path = "github.com/imfing/hextra" 
