baseURL = 'https://www.fuentederecho.com.ar/'
languageCode = 'es-ar'
title = 'Fuente de Derecho'

[menu]
  [[menu.main]]
    identifier = "Ley"
    name = "Ley"
    url = "/ley/"
    weight = 1
  [[menu.main]]
    identifier = "Jurisprudencia"
    name = "Jurisprudencia"
    url = "/jurisprudencia/"
    weight = 2
  [[menu.main]]
    identifier = "Doctrina"
    name = "Doctrina"
    url = "/doctrina/"
    weight = 3
  [[menu.main]]
    identifier = "Novedades"
    name = "Novedades"
    url = "/novedades/"
    weight = 4

[module]
[[module.imports]]
path = "github.com/imfing/hextra"